# Generated by Django 4.2.17 on 2025-01-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperature_db',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
